[package]
name = "clipboard-summarizer"
version = "0.1.0"
edition = "2018"

[dependencies]
arboard = "3.2"
chrono = "0.4"
tokio = { version = "1.0", features = ["full"] }
systray = "0.3"
sled = "0.34"
pulldown-cmark = "0.9"
